### ISSUE TITLE
Lock the last item

### ISSUE THREAD

**Issue by lbrsilva-allin** [yuyakaido/CardStackView#10]
Add the code:

                        if (distance < distanceBorder || topIndex == adapter.getCount() - 1) {
                            cardAnimator.moveToOrigin();
                        } else {
                            discard(direction);
                        }

in line 148 in the class CardStackView

**Comment by yuyakaido** [comment]
@lbrsilva-allin Thank you for your proposal. This feature has included in [ver. 1.0.0](https://github.com/yuyakaido/CardStackView/pull/14).
We can lock card using SwipeEnabled.

**Comment by yuyakaido** [comment]
@lbrsilva-allin Ver 1.0.0-beta1 has been released! Would you check [the feature to disable swipe](https://github.com/yuyakaido/CardStackView#swipeenabled)?
