### ISSUE TITLE
How to set background for top card ?

### ISSUE THREAD

**Issue by at-duymai** [yuyakaido/CardStackView#101]
I have a question about that. Is supported ? Thank you.

**Comment by luongvo** [comment]
@at-duymai this lib using adapter to render to cards, let change it in your adapter

**Comment by at-duymai** [comment]
Yes. I know that. But i want change only one card is head. Like we have list with 1-2-3
Now 1 is head and only 1 change background.
when i swipe and now 2 is head and 2 change background. 
Adapter render all card. how to check it ?

**Comment by luongvo** [comment]
@at-duymai The easiest way is wrap the card view into adapter data list, then set the background in card swiped event

**Comment by at-duymai** [comment]
@luongvo  Thank you for your supported.

**Comment by yuyakaido** [comment]
@at-duymai 
[Ver. 2.0.0](https://github.com/yuyakaido/CardStackView/pull/137) is based on RecyclerView, so you can use `ViewType` to implement this feature.

@luongvo 
Thank you for your support!
