### ISSUE TITLE
appcompat runtime crash warning

### ISSUE THREAD

**Issue by yavuzyurtbegendi** [yuyakaido/CardStackView#103]
All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.1.1, 25.4.0. Examples include com.android.support:animated-vector-drawable:27.1.1 and com.android.support:support-media-compat:25.4.0

**Comment by emreakcan** [comment]
Please try to use
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:support-v4:27.1.1'
.. (other custom libraries)
..

as explained at your error, all must be 27.1.1

**Comment by yavuzyurtbegendi** [comment]
https://github.com/yuyakaido/CardStackView/blob/master/cardstackview/build.gradle
this one is actually blocking me, you mean to override it right ? v4 is only needed for this library, I wanted to talk about migrating to v7 if any response was given :) I have done some changes to library and moved on, thanks for the answer

**Comment by yuyakaido** [comment]
@yavuzyurtbegendi 
You can resolve this problem with [ResolutionStrategy](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html).
