### ISSUE TITLE
Start Drag Manually

### ISSUE THREAD

**Issue by navi63** [yuyakaido/CardStackView#104]
Hi Sir.
I want to start draging the card with manual action.
how can i do this?

Thanks

**Comment by emreakcan** [comment]
It is explained in sample. Please download the whole project and review.

**Comment by yuyakaido** [comment]
@navi63 
Sorry for late reply.
As @emreakcan says, You can start dragging by using [automatic swipe](https://github.com/yuyakaido/CardStackView#automatic-swipe).
