### ISSUE TITLE
[PLEASE HELP]how to add some code when card is swiped left or right?

### ISSUE THREAD

**Issue by xXCHINNAXx** [yuyakaido/CardStackView#109]
i want to add some code when card is swiped left or right.

for example i want to display a toast message "left" when card is swiped left and same to right.

please help me.

**Comment by ivancse58** [comment]
You have to implement new CardStackView.CardEventListener().
See the bellow code:



            binding.cardStackView.setCardEventListener(new CardStackView.CardEventListener() {
            @Override
            public void onCardDragging(float percentX, float percentY) {
                Log.d("CardStackView", "onCardDragging");
                Log.d("CardStackView", "percentX: " + percentX);
                Log.d("CardStackView", "percentY: " + percentY);}

            @Override
            public void onCardSwiped(SwipeDirection direction) {
                Log.d("CardStackView", "onCardSwiped: " + direction.toString());
                if(SwipeDirection.Left == direction){
                    /*DO what you want to do*/
					//You can use eventBus to raise a event
					//eventBus.post(new LeftSwipeEvent());
                }
                if(SwipeDirection.Right == direction){
                    /*DO what you want to do*/
					//You can use eventBus to raise a event
					//eventBus.post(new RightSwipeEvent());
                }
            }

            @Override
            public void onCardReversed() {
                Log.d("CardStackView", "onCardReversed");
            }

            @Override
            public void onCardMovedToOrigin() {
                Log.d("CardStackView", "onCardMovedToOrigin");
            }

            @Override
            public void onCardClicked(int index) {
                Log.d("CardStackView", "onCardClicked: " + index);
                
            }
        });

**Comment by xXCHINNAXx** [comment]
thanks bro

now bro how to do multiple reversing the card ??

**Comment by kushsaurava** [comment]
using  BaseAdapter  will allow you to use  mCardView.setMultipleReverseEnabled(true)

**Comment by yuyakaido** [comment]
@xXCHINNAXx 
As @ivancse58 says, You should implement callback.
And, [ver. 2.0.0](https://github.com/yuyakaido/CardStackView/pull/137) supports multiple rewind.
