### ISSUE TITLE
Unable to find reverse method in library

### ISSUE THREAD

**Issue by NooruddinLakhani** [yuyakaido/CardStackView#11]
I am integrating this library for card stack and there I want to use reverse card method but i couldn't find it. Please help me out with this

**Comment by taosimple** [comment]
see that by 'git log', the function is delete before

**Comment by yuyakaido** [comment]
@NooruddinLakhani @taosimple Sorry for late reply.

I tried to refactor in early of this 2017, but Q1 - Q2 in 2017 is very busy for me. So I can't take the time to do it...

Now, some work in progress commits reverted and released 0.7.9. (0.7.9 is same as 0.7.7.)
