### ISSUE TITLE
How to adjust dragging sensitivity

### ISSUE THREAD

**Issue by emreakcan** [yuyakaido/CardStackView#110]
I think default is too fast. I want to decrease the sensitivity. 
Thanks

**Comment by vbuberen** [comment]
Hi there.
You should change Swipe Threshold property to adjust sensitivity.
https://github.com/yuyakaido/CardStackView#swipethreshold

**Comment by yuyakaido** [comment]
@emreakcan 
Sorry for late reply.
As @vbuberen says, You can adjust dragging sensitivity by using [swipe threshold](https://github.com/yuyakaido/CardStackView#swipe-threshold).
