### ISSUE TITLE
Multiple ViewType

### ISSUE THREAD

**Issue by jemshit** [yuyakaido/CardStackView#112]
Hi, i have problem when implementing multiple ViewType with `BaseAdapter` (or `ArrayAdapter<>`). 

```kotlin
class MyAdapter(private val context: Context) : BaseAdapter() {

    private val layoutInflater: LayoutInflater = LayoutInflater.from(context)
    private var items: MutableList<BaseAdModel> = mutableListOf()

    override fun getViewTypeCount(): Int = ViewType.values().size

    override fun getItemViewType(position: Int): Int {
        return if (items[position].isAd)
            ViewType.VIEW_TYPE_CARD_AD.ordinal
        else
            ViewType.VIEW_TYPE_CARD_ITEM.ordinal
    }

    override fun getItem(position: Int): Any = items[position]

    override fun getItemId(position: Int): Long = position.toLong()

    override fun getCount(): Int = items.size

    override fun getView(position: Int, contentView: View?, parent: ViewGroup): View {
        val inflatedView: View

        when (getItemViewType(position)) {
            ViewType.VIEW_TYPE_CARD_AD.ordinal -> {
                val adModel = items[position] as AdModel
                val viewHolderAdItem: ViewHolderAdItem

                // Get ViewHolder
                if (contentView == null || contentView.tag !is ViewHolderAdItem) {
                    viewHolderAdItem = ViewHolderAdItem()
                    inflatedView = getInflatedLayoutForType(getItemViewType(position), parent)
                    viewHolderAdItem.adView = inflatedView.findViewById(R.id.adViewNative)
                    inflatedView.tag = viewHolderAdItem

                } else {
                    inflatedView = contentView
                    viewHolderAdItem = inflatedView.tag as ViewHolderAdItem
                }

                // ReFill
                viewHolderAdItem.adView.setupAndLoadAds(adModel.id)
            }

            ViewType.VIEW_TYPE_CARD_ITEM.ordinal -> {
                val feedModel = items[position] as FeedModel
                val viewHolderFeedItem: ViewHolderFeedItem

                // Get ViewHolder
                if (contentView == null || contentView.tag !is ViewHolderFeedItem) {
                    viewHolderFeedItem = ViewHolderFeedItem()
                    inflatedView = getInflatedLayoutForType(getItemViewType(position), parent)
                    viewHolderFeedItem.itemView = inflatedView.findViewById(R.id.adView)
                    inflatedView.tag = viewHolderFeedItem

                } else {
                    inflatedView = contentView
                    viewHolderFeedItem = inflatedView.tag as ViewHolderFeedItem
                }

                // ReFill
                viewHolderFeedItem.itemView.setItem(feedModel)
            }

            else -> {
                // same as above case
            }
        }

        return inflatedView
    }
    //endregion

    private fun getInflatedLayoutForType(type: Int, parent: ViewGroup): View {
        return if (type == ViewType.VIEW_TYPE_CARD_AD.ordinal) {
            layoutInflater.inflate(R.layout.item_native_ad, parent, false)
        } else {
            layoutInflater.inflate(R.layout.item_feed, parent, false)
        }
    }
}

private class ViewHolderFeedItem {
    lateinit var itemView: FeedItemView
}

private class ViewHolderAdItem {
    lateinit var adView: NativeAdView
}

enum class ViewType {
    VIEW_TYPE_CARD_ITEM, VIEW_TYPE_CARD_AD
}
```

item_native_ad.xml
```xml
<...FeedItemView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/adView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"/>
```

item_feed.xml
```xml
<...NativeAdView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/adViewNative"
    android:layout_width="match_parent"
    android:layout_height="match_parent"/>
```

**Problem is**: 
Normally, `getView()` must give correct `contentView:View?` type as argument if only `getViewTypeCount()` returns correct number of view types. I return 2 in `getViewTypeCount()` thus `getView()` must give me correct `contentView:View?` type per position. But it does not for some reason, so i also check `contentView.tag !is ViewHolderFeedItem` and `contentView.tag !is ViewHolderAdItem`, because it does not give me correct `contentView`. If i don't do this control, it crashes because of `ClassCastException` at `inflatedView.tag as ViewHolderFeedItem`. 

Even after that control, CardStack does not show me correct View after some swipes, it shows `ViewHolderAdItem` instead of `ViewHolderFeedItem`. I have checked if model is correct and it is. I have checked if returned `inflatedView` in `getView()` is correct and it is. But still i see different xml view on CardStack.

I have also tried **not** overriding `getViewTypeCount()` and `getItemViewType()`, then inflating correct View without ViewHolder pattern in `getView()`, still i see wrong xml content in cardStack.

I suspect there is incorrect implementation in `CardStackView.java`, maybe when calling [getView manually?](https://github.com/yuyakaido/CardStackView/blob/master/cardstackview/src/main/java/com/yuyakaido/android/cardstackview/CardStackView.java#L502)

**Comment by jemshit** [comment]
I found there is pull request regarding to this: https://github.com/yuyakaido/CardStackView/pull/91

**Comment by ElteHupkes** [comment]
There is a workaround for this problem that doesn't require touching the library. Looking at [the code](https://github.com/yuyakaido/CardStackView/blob/master/cardstackview/src/main/java/com/yuyakaido/android/cardstackview/CardStackView.java#L182), we can see that the newly created view is added to the container when it doesn't currently have any children. So, in your adapter, when you intend to return a new view rather than reuse the old one, remove the old view from the also passed parent view to force your new view to be inserted.

**Comment by yuyakaido** [comment]
@jemshit @ElteHupkes 
This issue has been fixed in [ver. 2.0.0](https://github.com/yuyakaido/CardStackView/pull/137).

**Comment by ElteHupkes** [comment]
@yuyakaido Awesome! I see some other useful changes too, thanks :).
