### ISSUE TITLE
Disable swiping in a particular direction

### ISSUE THREAD

**Issue by WilBajamas** [yuyakaido/CardStackView#117]
Hi, thanks for the library, really awesome, and saved me a lot of time.
But may I know is it possible to disable a certain direction?\
Because I am using "freedom_nobottom", but I want to disable swipe up and enable swipe bottom.
Can I do that, please let me know thanks....

**Comment by yuyakaido** [comment]
@WilBajamas 
Thank you for your comment!
You can disable swiping in a particular direction by using [swipe restriction](https://github.com/yuyakaido/CardStackView#swipe-restriction).

**Comment by Sanaebadi97** [comment]
hi, I have This problem. I use Fab for back and Next  And Want To disable The Touch Swipe How Can I do It?

I use 
```
 manager.setCanScrollHorizontal(false);
    manager.setCanScrollVertical(false);
```

But The All Swipe disabled. I can not use fab for it.
