### ISSUE TITLE
Unable to reverse more than one Card

### ISSUE THREAD

**Issue by ECD00UFA** [yuyakaido/CardStackView#119]
I have been trying to reverse cards one by one but the behavior is a bit confusing. either i am able to swipe only one card or go directly to top of the Stack having gone through this #53 

what i want is to reverse the card one by one on a button click.

Moreover how may i achieve some animation on Reverse?

**Comment by kushsaurava** [comment]
using BaseAdapter will allow you to use mCardView.setMultipleReverseEnabled(true)

**Comment by yuyakaido** [comment]
@ECD00UFA @kushsaurava 
Sorry for late reply.
You can rewind more than one card by using [ver. 2.0.0](https://github.com/yuyakaido/CardStackView/pull/137).
