### ISSUE TITLE
Infinity phone layout issue

### ISSUE THREAD

**Issue by shikha1992** [yuyakaido/CardStackView#120]
for android phone with infinity layout, stack at bottom/top is not showing properly. I am using carddview for each item to add shadow in card, but its not displaying for infinity layout devices.

**Comment by yuyakaido** [comment]
@shikha1992 
Sorry, I can't understand your use case.
[Ver. 2.0.0](https://github.com/yuyakaido/CardStackView/pull/137) has been released with some new features. Try it out!
