### ISSUE TITLE
Is this repo no longer maintained?

### ISSUE THREAD

**Issue by cgomezmendez** [yuyakaido/CardStackView#122]
Last commit was 5 months ago and there is a lot of PR open, I was wondering is this is still maintained or not

**Comment by eirtaza** [comment]
Sorry to say, such a nice repo was commited 10 months ago.

**Comment by cnmicha** [comment]
@luongvo Please leave a comment when you started! 😃

**Comment by yuyakaido** [comment]
@cgomezmendez @eirtaza @luongvo @cnmicha 
Sorry for late reply.
I have been able to maintain this library because of my hard work...

Ver. 2.0.0 has been released with a lot of bug fixes and some new features.
And, I have re-implemented this library based on RecyclerView.
