### ISSUE TITLE
How to move to a specific position of cardStackView

### ISSUE THREAD

**Issue by uzairayub** [yuyakaido/CardStackView#124]
I want to move my cardstackview from a position to another position but I dont want to remove item from my ArrayList.
e.g my cardstackview current top position is 3 now I want the current top to 10th position but item should not delete from my arraylist.

**Comment by yuyakaido** [comment]
@uzairayub 
Sorry for late reply.
You can move to a specific position without removing any items from ArraryList by using `CardStackView.scrollToPosition` or `CardStackView.smoothScrollToPosition` in [2.0.0](https://github.com/yuyakaido/CardStackView/pull/137).

**Comment by uzairayub** [comment]
Thanks you for your reply @yuyakaido :+1:
