### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'android.view.ViewParent android.view.ViewParent.getParent()' on a null object reference

### ISSUE THREAD

**Issue by BasharAlhalabi** [yuyakaido/CardStackView#127]
Hi,
very helpful view.
I'm sure you forgot to validate against null values under:

 switch (MotionEventCompat.getActionMasked(event)) {
            case MotionEvent.ACTION_DOWN:
                handleActionDown(event);
                getParent().getParent().requestDisallowInterceptTouchEvent(true);
                break;
            case MotionEvent.ACTION_UP:
                handleActionUp(event);
                getParent().getParent().requestDisallowInterceptTouchEvent(false);
                break;
            case MotionEvent.ACTION_CANCEL:
                getParent().getParent().requestDisallowInterceptTouchEvent(false);
                break;
            case MotionEvent.ACTION_MOVE:
                handleActionMove(event);
                break;
        }

"getParent().getParent()." is a big source of null-exceptions in my case (till now the only one in this view). It happens basically when swiping relatively fast.

**Comment by jcharles8246** [comment]
I think there is a PR waiting to be merged in but it seems that this project is not currently being maintained...

https://github.com/yuyakaido/CardStackView/pull/62

**Comment by yuyakaido** [comment]
@BasharAlhalabi @jcharles8246 
This problem has been fixed in [ver. 2.0.0](https://github.com/yuyakaido/CardStackView/pull/137).
