### ISSUE TITLE
androidx cardview not working

### ISSUE THREAD

**Issue by Kalakrishnankr** [yuyakaido/CardStackView#129]
Androidx card view ( androidx.cardview.widget.CardView )not supporting this library.Could you please add

**Comment by jkauppin** [comment]
Tested with `android.enableJetifier=true` in` gradle.properties` and CardView works with AndroidX as well. Good to migrate to AndroidX some day but not that urgent right now I think.

**Comment by yuyakaido** [comment]
@Kalakrishnankr @jkauppin 
We have migrated to AndroidX in [ver. 2.3.3](https://github.com/yuyakaido/CardStackView/releases/tag/v2.3.3).
