### ISSUE TITLE
Insufficient customization ( no access to private container )

### ISSUE THREAD

**Issue by ElliotCrane** [yuyakaido/CardStackView#130]
This project doesn't support access to it's private card container and doesn't provide equivalent methods to manage card stacks except reverse(), getTopView() and getBottomView() which are very insufficient when you want to customize the swiping function.

**Comment by yuyakaido** [comment]
@ElliotCrane 
`CardContainerView` is not for public use, so it is not exposed as a public method.

----

[Ver. 2.0.0](https://github.com/yuyakaido/CardStackView/pull/137) has some new features to customize card stack.
If you want to more new features, please create new issue includes your usecase.
