### ISSUE TITLE
Library creates problem with the new gradle version 

### ISSUE THREAD

**Issue by akhileshjangid** [yuyakaido/CardStackView#131]
I've updated android studio to 3.2 with the gradle (3.4+) after that recompiling whole project. library creates issue:

 [Cause: com.novoda.gradle.release.AndroidLibrary$LibraryUsage.getDependencyConstraints()Ljava/util/Set; ]

I don't what's causing issue! whether the library module cardstackview is incompatible or what? but it doesn't seems to work out with the latest gradle build as I've read many questions and issues regarding the same but there's no  proper solution other than lowering the gradle version.

Any help appreciated
Thanks

 
![error](https://user-images.githubusercontent.com/28339446/46271059-5e0d4a00-c568-11e8-8fe6-c28d284346de.png)

**Comment by yuyakaido** [comment]
@akhileshjangid 
Sorry for late replay.
This issue has been fixed in 2.0.0.
