### ISSUE TITLE
Customization request on swipe up

### ISSUE THREAD

**Issue by NegassaB** [yuyakaido/CardStackView#134]
I want to customize this library to include it in my project. My customization would be when I swipe up on an item, I want it to go to a chat interface. Is that kind of customization possible? And how would one go about it?

**Comment by yuyakaido** [comment]
@NegassaB 
Sorry, I can't understand your use case.
[Ver. 2.0.0](https://github.com/yuyakaido/CardStackView/pull/137) has been released right now. Try it out.
