### ISSUE TITLE
Scroll cardStackView to bottom (below the next card's bottom) will fixed the location and can't reset.

### ISSUE THREAD

**Issue by jiao08** [yuyakaido/CardStackView#139]
Hi, I find a bug when touch and scroll the cardview:(I download the sample and build in android studio )
Touch down the cardStackView and scroll to bottom below the next cardview(eg: below 5--10dp), and raise up the finger(MotionEvent.ACTION_UP),  the cradStackView would be fixed the location and can't reset its origin location (the callback method--- onCardCanceled  is not called in the logcat)

   set  Relativelayout(cardStackView's parent) from 20dp to 60dp(or more)(android:padding="60dp")
   and the same situation exists when scroll to right.

PS: this situation doesn't exist when scroll to top/left up to now.
 
Could you tell me how to fix this bug？
Thank you very much!!!

**Comment by jiao08** [comment]
The situation which I said is like this:
![image](https://user-images.githubusercontent.com/25283651/48989252-64810200-f164-11e8-9949-457aa7a1776a.png)
Can you find this on your cellphone? 
Thanks!

**Comment by jiao08** [comment]
@yuyakaido 
Hi, can you find this bug? 
It still exists.

**Comment by yuyakaido** [comment]
@jiao08 
This issue has been fixed in [ver. 2.3.0](https://github.com/yuyakaido/CardStackView/releases/tag/v2.3.0).
