### ISSUE TITLE
Video on different cards play simultaniously

### ISSUE THREAD

**Issue by eirtaza** [yuyakaido/CardStackView#140]
While implementing video cards, i happened to notice that if video is configured to be played automatically (like instagram), it will start on the cards which are below the top card.

How can we implement it so the video is played automatically only if card comes to the top.

**Comment by yuyakaido** [comment]
@eirtaza 
Currently, there is no way to implement this feature.
But, I have a plan to add a following callback method for this situation.
`CardStackViewListener.onCardDisplayed(int position);`

**Comment by yuyakaido** [comment]
@eirtaza 
`CardStackViewListener.onCardAppeared/Disappeared` have been added in ver. 2.2.0.
