### ISSUE TITLE
Change cards only through the buttons not by swiping

### ISSUE THREAD

**Issue by AnkitTailoredTech** [yuyakaido/CardStackView#142]
Hi,

I want to change the cards by clicking on the buttons only and disable the swipe completely. 
I do not find the setSwipeEnabled(true/false) method. Also if I disable the swiping on both Horizontal and Vertical [setCanScrollHorizontal(false) and setCanScrollVertical(false)] then clicking on the buttons, swipe does not work. Can you please help me on this ?

**Comment by yuyakaido** [comment]
@AnkitTailoredTech 
Sorry for late reply.
Currently, there is no way to implement your use case.

**Comment by theGlenn** [comment]
Hey @AnkitTailoredTech, not ideal but one possible workaround is to keep `setCanScrollHorizontal(false)` and `setCanScrollVertical(false)` and right before calling `stackView.swipe()` re-enable scrolling then disable it again after in CardStackListener's `onCardSwiped`.


```kt
private fun CardStackLayoutManager.setCanInteract(canInteract: Boolean) {
   setCanScrollHorizontal(canInteract)
   setCanScrollVertical(canInteract)
}
....
   cardsStackLayoutManager.setCanInteract(true)
   membersViewerStackView.swipe()
....

override fun onCardSwiped(direction: Direction?) {
   cardsStackLayoutManager.setCanInteract(false)
}

```

**Comment by Sanaebadi97** [comment]
I have This Problem Too ... What SHould To do Now ???

**Comment by yuyakaido** [comment]
@AnkitTailoredTech @theGlenn @Sanaebadi97 
This feature is implemented by [Swipeable Method](https://github.com/yuyakaido/CardStackView#swipeable-method) in [ver. 2.3.0](https://github.com/yuyakaido/CardStackView/releases/tag/v2.3.0).
We should specify `Automatic` as a swipeable method to change cards only through buttons.

```
CardStackLayoutManager.setSwipeableMethod(SwipeableMethod.Automatic)
```
