### ISSUE TITLE
Reloading the list with the Adapter doesn't reset CardStackView

### ISSUE THREAD

**Issue by andreperegrina** [yuyakaido/CardStackView#143]
I try resetting the data with the `notifyDataSetChanged` but It doesn't work:
```
adapter?.setList(createList())
adapter?.notifyDataSetChanged()
```
It just work the first time I created the list.

**Comment by xcc3641** [comment]
I have this problem too

**Comment by BMak0917** [comment]
Hello, I have also faced this problem can you please give me some solution?

**Comment by yuyakaido** [comment]
Sorry for all.
This bug has been fixed in Ver. 2.1.0.
If you want to know more information, please see [Paging](https://github.com/yuyakaido/CardStackView#paging) or [Reloading](https://github.com/yuyakaido/CardStackView#reloading) section in README.
