### ISSUE TITLE
How can i implement pagination with cardStackView

### ISSUE THREAD

**Issue by goswamiji0** [yuyakaido/CardStackView#144]
Hello
I want to implement pagination with your library. is there any way to add pagination in CardStackView

**Comment by yuyakaido** [comment]
@goswamiji0 
You can implement pagination by adding items to adapter and calling `notifyDataSetChanged`.
[Sample app](https://github.com/yuyakaido/CardStackView/blob/master/sample/src/main/java/com/yuyakaido/android/cardstackview/sample/MainActivity.java) contains the implementation of pagination.
