### ISSUE TITLE
xml attribute linking problem

### ISSUE THREAD

**Issue by chanjungkim** [yuyakaido/CardStackView#149]
I struggled with this issue...

You just need to include more gradle library in build.gradle.

```
    implementation 'com.github.bumptech.glide:glide:4.8.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'
    implementation 'com.android.support:cardview-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'
```

**Comment by yuyakaido** [comment]
@chanjungkim 
This library only depends on RecyclerView, so you don't have to import these libraries.
You maybe import sample app of this repository.
