### ISSUE TITLE
What is analog for topView? (Ver. 2.1)

### ISSUE THREAD

**Issue by iRYO400** [yuyakaido/CardStackView#151]
or any examples that can be implemented within RVAdapter

**Comment by yuyakaido** [comment]
@iRYO400 
I don't know the meaning of `analog`.
Can you tell me more details?

If you want to implement custom view in this library, I can use `onCreateViewHolder` and `onBindViewHolder` of RecyclerView.Adapter. And you can get more information about custom view from [sample app](https://github.com/yuyakaido/CardStackView/tree/master/sample).

**Comment by iRYO400** [comment]
I mean, some migration tips about a var named topView inside CardStackView( was in version 1), so I can get a view that top over other cards.

**Comment by yuyakaido** [comment]
@iRYO400 
Sorry for late reply.
`CardStackLayoutManager.getTopView` has been added in ver. 2.2.0.

**Comment by iRYO400** [comment]
thanks! 
I tried implement by myself inside adapter
`return recyclerView.findViewHolderForLayoutPosition(0)!!.itemView`
If you know which one is better, I would be apreciated if you write it here
