### ISSUE TITLE
Cardview corners are not rounded and there is a padding in API level 16

### ISSUE THREAD

**Issue by YusufHussein** [yuyakaido/CardStackView#162]
Cardview corners are not rounded when tested in API level 16 and there seems to be some kind of padding inside the card around the image and the overlay
you can check this issue [here](https://stackoverflow.com/questions/32205044/android-layout-unwanted-padding) 
![screenshot_1544531997](https://user-images.githubusercontent.com/12372274/49801519-14549300-fd53-11e8-8f33-9350648d102c.png)

**Comment by yuyakaido** [comment]
@YusufHussein 
Thank you for your report!
This issue has been fixed in ver. 2.1.2.
