### ISSUE TITLE
Button click and finger touch conflict

### ISSUE THREAD

**Issue by JHwangxiaotian** [yuyakaido/CardStackView#175]
2.1.0-2.2.1  100% recurrence
Recurring process
1.Click the button first and then touch the CardView
2.After clicking the button, when the CardView has not moved out of the screen, clicking on the CardView with your finger will cause the button to be invalid (only this CardView)
3.After the finger moves out of the problematic CardView, the button returns to normal

**Comment by JHwangxiaotian** [comment]
V2.2.1
 click button -> cardStackView.rewind() 
 When the card has not been swiped to the predetermined position, hold the card with your finger and move it out. 
Then you will find that clicking the button or touching the card will not work.

**Comment by yuyakaido** [comment]
@JHwangxiaotian 
This issue has been fixed in ver. 2.2.2.
