### ISSUE TITLE
onBindViewHolder invoked frequently when drag the card

### ISSUE THREAD

**Issue by IsnoneTy** [yuyakaido/CardStackView#176]
CardStackLayoutManager use removeAndRecycleAllViews(recycler) in update(RecyclerView.Recycler recycler)

**Comment by rossica** [comment]
I have this same issue. The problem arises because onBindViewHolder invokes Glide to load the image on each call, and that makes the drag animation lag significantly.
No nested layout in the card layout.
I'll have to roll back to 1.x because this looks pretty bad.

**Comment by Pirksy** [comment]
I have the same issue

**Comment by Pirksy** [comment]
Downgraded to 2.0.0 version and problem gone

**Comment by chrisrohitbrendan** [comment]
@Pirksy 2.2.0 also works

**Comment by hockleongloh** [comment]
Is there any other way to solve nested layout issue? I downgraded to 2.0.0 but the issue still remain

**Comment by taomWTP** [comment]
@yuyakaido please review merge #171. `removeAndRecycleAllViews(recycler)` causes instantiating all views again. Consider to replace it with `detachAndScrapAttachedViews(recycler)`

**Comment by yuyakaido** [comment]
@IsnoneTy @vphuong1205 @rossica @Pirksy @chrisrohitbrendan @hockleongloh @taomWTP 
Sorry for late reply. This issue has been fixed in [ver. 2.2.4](https://github.com/yuyakaido/CardStackView/releases/tag/v2.2.4).

@taomWTP 
Thank you so much for your helpful advice!
