### ISSUE TITLE
How to cancel dragging programmatically

### ISSUE THREAD

**Issue by alexeykozlov07** [yuyakaido/CardStackView#179]
I am looking for function to cancel dragging in onCardDragging listener.
ex:
```
@Override
public void onCardDragging(Direction direction, float ratio) {
       if (pageIndex == 5){
             cardStackView.cancelDragging();
       }
}
```

**Comment by alexeykozlov07** [comment]
> I am looking for function to cancel dragging in onCardDragging listener.
> ex:
> 
> ```
> @Override
> public void onCardDragging(Direction direction, float ratio) {
>        if (pageIndex == 5){
>              cardStackView.cancelDragging();
>        }
> }
> ```

**Comment by yuyakaido** [comment]
@alexeykozlov07 
You can disable dragging programmatically by using [Swipe Restriction](https://github.com/yuyakaido/CardStackView#swipe-restriction).
