### ISSUE TITLE
Overlay applies to CardStackView instead of just the CardView

### ISSUE THREAD

**Issue by kndl22** [yuyakaido/CardStackView#18]
Hey,
First, very nice work with this library!

I'm trying to achieve overlay effect only at the CardView, e.g: changing its color while swiping left/right.
Currently the color change effects all the  CardStackView and it looks bad if you have a CardView which is half size the total CardStackView.

 Also, is it possible to add overlay effect to top/bottom drag aswell?

**Comment by kndl22** [comment]
I've managed to solve it, not sure if this is the best practice for this issue:

- Created a CardView for overlay_left & overlay_right which include the same layout as my main CardView, setting it's main layout as visibily:invisible - to keep the views with the same bounds.

**Comment by yuyakaido** [comment]
@kndl22 Thank you for your report!

> I'm trying to achieve overlay effect only at the CardView, e.g: changing its color while swiping left/right.
> Currently the color change effects all the CardStackView and it looks bad if you have a CardView which is half size the total CardStackView.

You can solve this issue to create overlay layout that has same height of content.

If you created content layout like below.
```
<android.support.v7.widget.CardView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:card_view="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="400dp"
    app:cardUseCompatPadding="true"
    card_view:cardCornerRadius="8dp"
    card_view:cardBackgroundColor="@android:color/white">
    
    <!-- Content -->
    
</android.support.v7.widget.CardView>
```

Try to create overlay layout that has same height.
```
<android.support.v7.widget.CardView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="400dp"
    app:cardBackgroundColor="#88000000"
    app:cardCornerRadius="8dp"
    app:cardElevation="0dp"
    app:cardUseCompatPadding="true">

    <!-- Overlay -->

</android.support.v7.widget.CardView>
```

**Comment by yuyakaido** [comment]
@kndl22 
> Also, is it possible to add overlay effect to top/bottom drag aswell?

Thank you for your proposal and [contribution](https://github.com/yuyakaido/CardStackView/pull/19).
Ver. 1.0.0-beta3 has been released including this feature.
