### ISSUE TITLE
adapter.notifyDataSetChanged() BUG

### ISSUE THREAD

**Issue by lvpeng0412** [yuyakaido/CardStackView#185]
v2.2.2 when use adapter.notifyDataSetChanged() ,will display the first item 
v2.0.0 No such problem

**Comment by lvpeng0412** [comment]
@Override
        public void onCardSwiped(Direction direction) {
            adapter.addSpots(spots);
            adapter.notifyDataSetChanged();
}

**Comment by lvpeng0412** [comment]
@yuyakaido

**Comment by kolllor33** [comment]
In Reloading in the README it says that adapter.notifyDataSetChanged(); will reset the position of the current position to the first one(it will reset the position counter). so only call this when you have new data and want to start from the start index again. I had the same problem i think so just remove adapter.notifyDataSetChanged(); this line in the onswipe event and it will work again i think.

**Comment by yuyakaido** [comment]
@lvpeng0412 
Resetting the top position when you call `notifyDataSetChanged` is intended behavior. If you don't want to reset the top position, you should use `DiffUtil` or call `notifyItemRangeInserted` manually. You can get more detail information from [paging section](https://github.com/yuyakaido/CardStackView#paging) in README.

@kolllor33 
Thank you for your comment!
