### ISSUE TITLE
Design is not displayed same in every device

### ISSUE THREAD

**Issue by Dipan8866** [yuyakaido/CardStackView#186]
Before the Layout Manager was introduce the library my UI looks similar in all the devices but after the introduction of layout manager my UI gets changed unconditionally based on the device sizes.

**Comment by yuyakaido** [comment]
@Dipan8866 
I can't reproduce this issue.
Can you tell me more detail information and some screenshots?

**Comment by yuyakaido** [comment]
@Dipan8866 
I can't reproduce the issue in my environment. If there is still a design problem, can you tell me more detail information and screenshots.
