### ISSUE TITLE
Differenciate which card was swiped if there are 2 stackView

### ISSUE THREAD

**Issue by ivanloy** [yuyakaido/CardStackView#187]
fun onCardSwiped(direction: Direction); 
                                to
 fun onCardSwiped(direction: Direction, view : View);

**Comment by yuyakaido** [comment]
@ivanloy I think it is't responsible for this library. Can you use two separated listeners?

**Comment by Slake07** [comment]
@yuyakaido How can we use two separated listeners in same class?
