### ISSUE TITLE
When Swipe Left/Right I want set Action

### ISSUE THREAD

**Issue by Sanaebadi97** [yuyakaido/CardStackView#189]
Hi, I want to set Some Action When The swipe to right/left. How can I do it?

**Comment by yuyakaido** [comment]
@Sanaebadi97 You can receive [some callbacks](https://github.com/yuyakaido/CardStackView#callbacks) from this library. If you want to set an action when swiping, you can use `CardStackListener.onCardSwiped(Direction direction)`.
