### ISSUE TITLE
I need one example on Java, is possible?

### ISSUE THREAD

**Issue by tobaleet17** [yuyakaido/CardStackView#195]
I only see one example in kotlin but i don't understand this language, have you a example on java?
Thanks.

**Comment by lahaiery** [comment]
If you go to the release history, version 2.20 has a sample application in java.

**Comment by tobaleet17** [comment]
> If you go to the release history, version 2.2.0 has a sample application in java.

Nice my friend, thanks for the info!!!!!

**Comment by GoldenCR7** [comment]
> If you go to the release history, version 2.2.0 has a sample application in java.

thank you
