### ISSUE TITLE
Swipe not smooth

### ISSUE THREAD

**Issue by hockleongloh** [yuyakaido/CardStackView#196]
Hi, when the subitem layout contains of lot of view component , it will laggy when I try to swipe.
It seems occur in low-spec devices.

Hope to get your reply ASAP.
Thanks.

Library version : 2.2.2
Device: Samsung Galaxy J2

**Comment by yuyakaido** [comment]
@hockleongloh 
It is important to make your layout flat to be smooth. You can use [ConstraintLayout](https://developer.android.com/reference/android/support/constraint/ConstraintLayout) to make layout flat and reduce layout cost.
