### ISSUE TITLE
Card flash

### ISSUE THREAD

**Issue by hockleongloh** [yuyakaido/CardStackView#197]
When i started to swipe or drag the card, it will keep on blink and flashing

Hope to get your reply ASAP.
Thanks.

Library version : 2.2.3

**Comment by hari2109** [comment]
What type of layout do you have within your card item? If there's any layout which is dynamically populated, that might be the issue.

**Comment by yuyakaido** [comment]
@hockleongloh @hari2109 
I can't reproduce this issue. But maybe this issue has been fixed in [ver. 2.2.4](https://github.com/yuyakaido/CardStackView/releases/tag/v2.2.4). There is a problem that Adapter.onBindViewHolder is invoked while dragging before ver. 2.2.4.
