### ISSUE TITLE
Is it possible to rewind by swiping in any of the available direction?

### ISSUE THREAD

**Issue by abhi9419** [yuyakaido/CardStackView#201]
Hi,

I am trying to rewind the cardstackview content using swipe from top to down, I wonder if this is possible.

**Comment by yuyakaido** [comment]
@abhi9419 
Currently, it is impossible to specify the direction of rewind.

**Comment by Death14Stroke** [comment]
> @abhi9419
> Currently, it is impossible to specify the direction of rewind.

Will this be added as an enhancement?

**Comment by yuyakaido** [comment]
@Death14Stroke 
Yes, I want to add this feature as an enhancement.
But I have no concrete roadmap.

**Comment by Death14Stroke** [comment]
Thank you for your response and such a great library.
