### ISSUE TITLE
while fast swiping app crashes ! 

### ISSUE THREAD

**Issue by kdblue** [yuyakaido/CardStackView#213]
v 2.2.4
I found this error log! 

java.lang.IllegalArgumentException: Tmp detached view should be removed from RecyclerView before it can be recycled: ViewHolder{4259b95 position=20 id=-1, oldPos=-1, pLpos:-1 tmpDetached no parent} com.yuyakaido.android.cardstackview.CardStackView{d5bea0d VFED..... .F.....D 60,60-1020,1548 #7f09005f app:id/card_stack_view},

**Comment by Grove221** [comment]
same issue , find any solution?

**Comment by kdblue** [comment]
@Grove221 yea, don't scroll fast 😁

**Comment by yuyakaido** [comment]
Duplication: https://github.com/yuyakaido/CardStackView/issues/198

**Comment by richanshah** [comment]
@yuyakaido  how to resolve this issue
