### ISSUE TITLE
Multidimensional Stack

### ISSUE THREAD

**Issue by recroj** [yuyakaido/CardStackView#215]
It would be great if we would have the possibility to define a stack to have multiple dimensions. e.g. StackFrom 'Right & Bottom', so that the stack also without any scaling would look like a stacked stack.

![sample-stack-from-right](https://user-images.githubusercontent.com/12171540/54591783-4436c500-4a2b-11e9-8a61-993c3a79f781.png)
![sample-stack-from-bottom](https://user-images.githubusercontent.com/12171540/54591784-46008880-4a2b-11e9-9b4a-7cc9f1e50890.png)

**Comment by recroj** [comment]
Created a PR for this, please review.

**Comment by yuyakaido** [comment]
@recroj 
Thank you so much for your contribution!
[Ver. 2.2.5](https://github.com/yuyakaido/CardStackView/releases/tag/v2.2.5) has been released including this feature.
