### ISSUE TITLE
 Illegal behavior when recyclerViewChild reuse from cache.

### ISSUE THREAD

**Issue by katsuya-yamada-eureka** [yuyakaido/CardStackView#222]
・Illegal behavior when recyclerViewChild reuse from cache.
・I Implemented card pagination. This bug occurred when I turned over the last card and next card is appeared.

**Comment by yuyakaido** [comment]
@katsuya-yamada-eureka 
This issue has been fixed in [ver. 2.2.6](https://github.com/yuyakaido/CardStackView/releases/tag/v2.2.6).
