### ISSUE TITLE
how to allow only swipe to top?

### ISSUE THREAD

**Issue by jamesvanhallen** [yuyakaido/CardStackView#225]
I want to prevent swipe to bottom in Vertical Mode.

**Comment by yuyakaido** [comment]
@jamesvanhallen 
We can implement this feature by using [Swipe Direction](https://github.com/yuyakaido/CardStackView#swipe-direction).
Can you put the following code in your project?
```
manager.setDirections(Arrays.asList(Direction.Top))
manager.setCanScrollHorizontal(false)
manager.setCanScrollVertical(true)
```

**Comment by jamesvanhallen** [comment]
<img width="472" alt="Screenshot 2019-03-31 at 13 09 27" src="https://user-images.githubusercontent.com/8998306/55287787-451a1000-53b6-11e9-89fd-1f730583e964.png">
<img width="730" alt="Screenshot 2019-03-31 at 13 09 48" src="https://user-images.githubusercontent.com/8998306/55287788-451a1000-53b6-11e9-806a-9c1ef3ecc44b.png">
Unfortunately, it's not working for me.

**Comment by jamesvanhallen** [comment]
`com.yuyakaido.android:card-stack-view:2.2.5`
