### ISSUE TITLE
View of card steck breaks after unlocking

### ISSUE THREAD

**Issue by P1NG2WIN** [yuyakaido/CardStackView#238]
After unlocking, the visible cards are superimposed on each other and this disappears after any movement. Does anyone know how to fix this? thank
![image](https://user-images.githubusercontent.com/27578886/56316486-b3065b80-615a-11e9-872e-f7018c1985a3.png)
![image](https://user-images.githubusercontent.com/27578886/56316508-b994d300-615a-11e9-8149-d77c1c9dcef0.png)

**Comment by yuyakaido** [comment]
@P1NG2WIN 
I can't reproduce this issue in my environment.
Can you send a sample project that we can reproduce this issue?

**Comment by P1NG2WIN** [comment]
@yuyakaido

It so happened that I had to roll back my project a few versions back and there is no this bug on the current one, but if it reappears, I will necessarily write

**Comment by yuyakaido** [comment]
@P1NG2WIN 
OK, Can you provide the following information when you write another issue?
- Device name
- OS version
- Library version that the issue happens
- Library version that the issue doesn't happen

**Comment by P1NG2WIN** [comment]
@yuyakaido
Ok, I was able to repeat it. You need to update the list. For example, this code breaks the cards display.

`testCardList.remove(testCard);
                    adapter.notifyItemRemoved(position);
                    adapter.notifyItemRangeChanged(position,adapter.getItemCount()-position);`

Xiaomi Redmi Note 4x
MIUI Global 10.2 (Android 7.0)
Library version 2.3.2 with bug

**Comment by P1NG2WIN** [comment]
So, this bug is caused by default animations RecyclerView's ItemAnimator so, to fix it, you need to disable it 
`cardStackView.setItemAnimator(null);`

_This bug is caused every time when standard RecyclerView animations are triggered, for example notifyItemRemoved, notifyItemAdded etc_
