### ISSUE TITLE
Pinch zoom

### ISSUE THREAD

**Issue by cnmicha** [yuyakaido/CardStackView#239]
Hi, could you please add an option to enable pinch zoom (two fingers) on the cards as it is done on Instagram for example? We're using an ImageView on the card and are currently trying to implement a zoom functionality.

**Comment by damien5314** [comment]
I'm not the library author, but it sounds like you want an ImageView implementation that does this, rather than being supported by this library. This library is a custom RecyclerView that doesn't really have anything to do with how the Views in the list behave 😅

**Comment by cnmicha** [comment]
@damien5314 Thank you for your suggestion. This what we already implemented as a workaround. 😅 But when zooming, the card itself does not become bigger. The effect we want to archieve is that the content size increases by zooming (this is already done by a custom ImageView implementation) and as soon as the image view becomes bigger than the card, its layout should not be cropped by the card layout borders, but overlap the shadows and anything around. We are using the CardStackView with some margin, so there is some space for the image to extend.
We're trying to archieve a similar pinch-zooming effect as Instagram (ImageView increases size and overlaps the TextViews below), but inside the cards of the CardStackView.

**Comment by yuyakaido** [comment]
@cnmicha 
Thank you for your proposal!
I know your use-case but I think this is not library's responsibility as @damien5314 mentioned. So I have no plan to implement this feature in this library.
