### ISSUE TITLE
How to set width and height to a particular size?

### ISSUE THREAD

**Issue by vadhmln** [yuyakaido/CardStackView#240]
Hi. guys!
I want to to set width and height to a particular size, like: 200dp; 250dp.
But when I set it in my item_spot layout and leave width and height to match_parent in cardstackview, nothing happing - The width and height are always set to  match_parent.
And when I set width and height in cardstackview to a particular size, like: 200dp; 250dp, the cards swiping inside this area (200dp; 250dp).

So, is it a bug or I do something wrong?  
Thanks for your awesome project!

**Comment by yuyakaido** [comment]
@vadhmln 
The correct way is that cardstackview has a particular size like width:200dp and height:250dp.And you should set `clipChildren=false` to parent of cardstackview.

**Comment by yuyakaido** [comment]
@vadhmln 
You can get more information from [sample app](https://github.com/yuyakaido/CardStackView/blob/master/sample/src/main/res/layout/activity_main.xml).
