### ISSUE TITLE
    java.lang.IndexOutOfBoundsException: Invalid item position 11(11). Item count:11 com.yuyakaido.andr

### ISSUE THREAD

**Issue by rastrish** [yuyakaido/CardStackView#242]
I am getting this error on adding more item to the list

**Comment by plhbao** [comment]
I am get this error,too.

**Comment by rastrish** [comment]
my issue is solved

**Comment by plhbao** [comment]
How did you solve it？

**Comment by yuyakaido** [comment]
@rastrish 
We need to use `DiffUtil` or call `notifyItemRangeInserted` when we add items to the list.
