### ISSUE TITLE
Ovelapping items

### ISSUE THREAD

**Issue by arctic4x** [yuyakaido/CardStackView#246]
On some devices i got overlapped items (as on picture)
Its 3 item on each other. Why did that happen?
If i drag cardstack the bigger item start moving and then gone
![image](https://user-images.githubusercontent.com/30060869/57387197-8d4efe00-71be-11e9-8068-9f9d292ad703.png)

**Comment by yuyakaido** [comment]
@arctic4x 
I can't reproduce this issue in my environment.
Can you send a sample project that we can reproduce this issue?

**Comment by arctic4x** [comment]
@yuyakaido nevermind, its videoview's problem :)
