### ISSUE TITLE
Show stack at top

### ISSUE THREAD

**Issue by sjla** [yuyakaido/CardStackView#261]
It's nice library,but i want to show stack at top and min count of stack to show should be 3,how can i achieve this.

**Comment by yuyakaido** [comment]
@sjla 
Thanks!
We can use [StackFrom](https://github.com/yuyakaido/CardStackView#stack-from) and [VisibleCount](https://github.com/yuyakaido/CardStackView#visible-count) to achieve the feature you mentioned.

**Comment by elifozoglu98** [comment]
Hello, I applied what you have said as : 
   manager.setStackFrom(StackFrom.Top);
    manager.setVisibleCount(3);

But still it wont show the stack from top. Any idea why?
