### ISSUE TITLE
Do I have to migrate to androidx to use this?

### ISSUE THREAD

**Issue by dinesh750** [yuyakaido/CardStackView#263]

**Comment by TayfunCesur** [comment]
I faced this issue. Also I haven't migrated my project to AndroidX yet. I looked the releases tab and saw this library has started to support AndroidX in the 2.3.3. 
So I downgrade the version to 2.3.2 and it worked for now. At least, I can work with this version until I migrate to AndroidX.

**Comment by damien5314** [comment]
What's the error? AndroidX is the new support library going forward, perhaps there is just some build configuration required to resolve a conflict

**Comment by TayfunCesur** [comment]
```
Manifest merger failed : Attribute application@appComponentFactory 
value=(android.support.v4.app.CoreComponentFactory)
from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
is also present at [androidx.core:core:1.0.0] 
AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:10:5-73:19 to override.
```
This is common error I think because I've seen it many times before. 
This happens when you want to use some library who supports AndroidX but your project doesn't support AndroidX.

**Comment by dinesh750** [comment]
> ```
> Manifest merger failed : Attribute application@appComponentFactory 
> value=(android.support.v4.app.CoreComponentFactory)
> from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
> is also present at [androidx.core:core:1.0.0] 
> AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
> Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:10:5-73:19 to override.
> ```
> 
> This is common error I think because I've seen it many times before.
> This happens when you want to use some library who supports AndroidX but your project doesn't support AndroidX.

Yes thats why I ask from you buddy
