### ISSUE TITLE
Card gets hanged

### ISSUE THREAD

**Issue by anirudh-springrole** [yuyakaido/CardStackView#27]
Thanks for the wonderful library.

I faced an issues in case we swipe the card partially to the bottom and without releasing our card if we minimise our app using the home button of device and come back again to the app, the card remains stuck and does not returns to the original position.

**Comment by yuyakaido** [comment]
@anirudh-springrole 
Thank you for your report!
I missed this case 😱
I will fix this issue in this weekend if possible.

**Comment by yuyakaido** [comment]
@anirudh-springrole Ver. 1.0.0-beta6 has been released including this issue. Try it out. 🙏

**Comment by anirudh-springrole** [comment]
This seems to have solved the issue. Thanks
