### ISSUE TITLE
Bug: Reloading doesn't work properly

### ISSUE THREAD

**Issue by geekytechie** [yuyakaido/CardStackView#272]
On reloading the CardStackView at the last position, the card get stucks in the air. Attached is the screenshot.

    @Override
    public void onCardDisappeared(View view, int position) {
        if(position == (arrayList.size()-1)){
            cardStackView.getAdapter().notifyDataSetChanged();
        }
    }

![device-2019-08-08-201355](https://user-images.githubusercontent.com/29394934/62713199-f6424e00-ba19-11e9-8578-f41ae3fa3a70.png)

**Comment by bashizip** [comment]
Try this instead 

```
   @Override
    public void onCardAppeared(View view, int position) {
        resetMap(yourList.get(position));
    }
```

And 

```
  @Override
    public void onCardSwiped(Direction direction) {
        if (layoutManager.getTopPosition() == (yourList.size())) {
            adapter.notifyDataSetChanged();
        }
    }
```

**Comment by yuyakaido** [comment]
@geekytechie 
We should implement reloading in `onCardSwiped` not in `onCardDisappeared` as @bashizip mentioned.
