### ISSUE TITLE
Scrollview inside cradStackView automatically get scrolled on swipe

### ISSUE THREAD

**Issue by ervinod** [yuyakaido/CardStackView#273]
I'm using scrollview inside CardStackView and every item has lots of content. When i swipe item to left or right next item is already scrolled ( scroll amount depends upon portion i have scrolled on previous item). Please solve this issue.
Thanx in advance...

**Comment by yuyakaido** [comment]
Duplication: https://github.com/yuyakaido/CardStackView/issues/105
