### ISSUE TITLE
Can't get item inside onCardSwiped, need to pass index, along with direction

### ISSUE THREAD

**Issue by robertBadamshin** [yuyakaido/CardStackView#274]

**Comment by 7hundeR** [comment]
I do, too. Thank you

**Comment by yoav-sadeh** [comment]
+1

**Comment by yuyakaido** [comment]
@robertBadamshin @7hundeR @yoav-sadeh 
We can get an item by using `CardStackLayoutManager.getTopPosition` or `CardStackLayoutManager.getTopView`.
