### ISSUE TITLE
how do I add listener for right or left swipe? 

### ISSUE THREAD

**Issue by alonsd** [yuyakaido/CardStackView#275]
I do not understand how do I add logic specific for left/right swipes, and in general how do I add listeners for swipes because I can't figure out where should the CardStackListener go into.

**Comment by bcho** [comment]
You can listen to `onCardSwiped(direction: Direction?)`, the direction tells about the swiped direction (left/right etc)

**Comment by alonsd** [comment]
Where do I add it? To the recyclerview itself or to the layoutmanager? Because I did not find it at either of them

**Comment by bcho** [comment]
See here: https://github.com/yuyakaido/CardStackView#callbacks
