### ISSUE TITLE
How can i assing a new activity to the swipe to right?

### ISSUE THREAD

**Issue by leslaliun** [yuyakaido/CardStackView#279]
Im stuck, i need you all help, how could i add that event in the tittle ? I have this:

`val newActivity= Intent(this, newActivity::class.java) `</br>`
 startActivity(newActivity)`

that works well with the like button, but i cant find out how to make it work with the swipe to right, i looked for the method `CardStackListener.onCardSwiped(Direction direction)` but my brain just cant,, can you give me a hand?

**Comment by yuyakaido** [comment]
@leslaliun 
As you mentioned, if you want to invoke any actions when a card is swiped, you need to put your codes in `CardStackListener.onCardSwiped(Direction direction)`. If you need more information, you can check [sample app](https://github.com/yuyakaido/CardStackView/blob/master/sample/src/main/java/com/yuyakaido/android/cardstackview/sample/MainActivity.kt).
