### ISSUE TITLE
how to make Infinity looping with same items

### ISSUE THREAD

**Issue by ixiDev** [yuyakaido/CardStackView#280]
Hi ,
Thanks for this project it's very powerful , please how to make Infinity looping with same items
in the last version

**Comment by yuyakaido** [comment]
@ixiDev 
This library is using an adapter of RecyclerView. If you want to make an infinity looping, you need to implement a loopable adapter as mentioned [here](https://stackoverflow.com/questions/31253555/how-do-i-create-a-circular-endless-recyclerview).
