### ISSUE TITLE
duplicates images

### ISSUE THREAD

**Issue by ravidr** [yuyakaido/CardStackView#281]
When using Picasso library to load images into the card,
if I swipe quickly, it shows previous images sometimes for a brief moment, like for a second,
it repeats loaded images, and when I stop to swipe, it loads the new image, like it supposed to.

how do I handle this issue?
thanks

P.S
tried Picasso memory policies method, not working

**Comment by yuyakaido** [comment]
@ravidr 
CardStackView(RecyclerView) recycles views so you should reset ImageView before loading the next image.
