### ISSUE TITLE
Swipe left for next and right for previous

### ISSUE THREAD

**Issue by tangiable** [yuyakaido/CardStackView#286]
Hello

How can I modify the library to enable moving to next card only on swipe left and move to previous card on swipe right?

Anyone has any ideas? Please suggest.

Thanks

AB

**Comment by yuyakaido** [comment]
@tangiable 
We can enable to move to the next card only on swipe left by [swipe direction](https://github.com/yuyakaido/CardStackView#swipe-direction). However, there is no way to move to the previous card on swipe right. Currently, I have no plan to implement this feature. But your contribution is always welcome.

**Comment by thebeingapp** [comment]
is there a way to navigate to another activity/fragment on swipe right while keeping swipe left as the default direction to move to next card?

**Comment by Zhangxd77** [comment]
I also encounter this problem. Does anyone know how to solve it? Thank you

**Comment by Zhangxd77** [comment]
I also encounter this problem. Does anyone know how to solve it? Thank you

**Comment by andrea-liu87** [comment]
Same here. anybody found the solution?
