### ISSUE TITLE
getting current object

### ISSUE THREAD

**Issue by ShrikantBadwaik-007** [yuyakaido/CardStackView#29]
Hi, wonderful library. I have a question, how do i get object for current card? Also, how do i disable top swipe?
Thanks.

**Comment by yuyakaido** [comment]
@ShrikantBadwaik-007 Thanks 😎

You can get top card by using `CardStackView#getTopView()`.
If you want to disable swipe, call `CardContainerView#setDraggable(boolean)`.

But, `CardContainerView#setDraggable(boolean)` is an internal API, so this is subject to change without notice in future release.

**Comment by ShrikantBadwaik-007** [comment]
method call you have mentioned gives me object of CardContainerView but that's not what i'm asking. Say, I have list of Profiles which i'm displaying in cardstackview, so how do i get object of Profile for the currently displayed card?

**Comment by yuyakaido** [comment]
@ShrikantBadwaik-007 Oh, I misunderstood.

CardStackView doesn't have a method to return object like a Profile. But, `CardStackView#getTopIndex()` returns top index of card stack, this index can be used as list index.

**Comment by dsuresh-ap** [comment]
@yuyakaido Would there be a point where getTopIndex() would return a value other than 0? Since it is a stack wouldn't the top index always be 0?

**Comment by dsuresh-ap** [comment]
@ShrikantBadwaik-007 When a card is swiped, I get the first item from my adapter

**Comment by yuyakaido** [comment]
@dsuresh-ap The name `getTopIndex` is a little confusing, this method returns adapter index displaying on top of card stack.

For example, 
- An adapter has 10 items
- You swiped twice
- Third card is displayed on top

In this situation, getTopIndex returns 3.

If you want to know more detail, please see sample app in this repository.

**Comment by jemshit** [comment]
Hi @yuyakaido , is there any way to get index of swiped item?

**Comment by dsuresh-ap** [comment]
@jemshit `getTopIndex() - 1` should return the index of the swiped Object in your adapter
