### ISSUE TITLE
Cannot set visibleCount to 1

### ISSUE THREAD

**Issue by barakhadar** [yuyakaido/CardStackView#32]
I set app:visibleCount="1"

**Expected result:** after the card was swiped all the way out of the screen, the next one will show.

**Current result:** as soon as the card is about to exit the screen, the app crushes.

**Comment by yuyakaido** [comment]
@barakhadar Thanks you for your report!
I try to fix it as soon as possible.

**Comment by yuyakaido** [comment]
@barakhadar Ver. 1.0.0-beta7 has been released including this issue. Please check it out.

**Comment by barakhadar** [comment]
Now it works great, thanks for an awesome library!
