### ISSUE TITLE
Disable card swipe TOP to Bottom direction when the top card in stack is the first card

### ISSUE THREAD

**Issue by ranasaha1212** [yuyakaido/CardStackView#320]
How can I disable TOP to BOTTOM direction swipe when the top card in the stack is the first card?
OR
How can I disable BOTTOM to TOP direction swipe when the top card in the stack is my last card? I cannot find any method to do that. Is there any way to achieve this logic in this library? Please help me out.

**Comment by ranasaha1212** [comment]
> How can I disable TOP to BOTTOM direction swipe when the top card in the stack is the first card?
> OR
> How can I disable BOTTOM to TOP direction swipe when the top card in the stack is my last card? I cannot find any method to do that. Is there any way to achieve this logic in this library? Please help me out.

**Comment by ranasaha1212** [comment]
Anyways, I have done changes in the module according to my requirement and have achieved to make the above mentioned functionality. So thanks. Though if you implement the above functionality in your module, it will be more elegant.

**Comment by mwshubham** [comment]
Can you share your finding?
