### ISSUE TITLE
Area for swipe

### ISSUE THREAD

**Issue by Monabr** [yuyakaido/CardStackView#322]
![88117416-be4d0000-cbc3-11ea-87ae-9d5881638878](https://user-images.githubusercontent.com/30532666/88479882-0751db00-cf5b-11ea-8dae-76fffaf79dfd.png)

The problem is, that card can be swiped on all the area not only in purple square. Fix this please.

**Comment by yuyakaido** [comment]
@Monabr 
The sample app of CardStackView has similar screen content and the card can be swiped only on purple area, so it seems CardStackView is not related to the problem.
