### ISSUE TITLE
Are cards being loaded asynchronically?

### ISSUE THREAD

**Issue by iWillBeUnderYourBed** [yuyakaido/CardStackView#331]
When I have a list of 10 items in my adapter, will 10 cards be created and are in memory at the same time?

**Comment by yuyakaido** [comment]
@iWillBeUnderYourBed 
No, this library is based on RecyclerView and only 3 cards are created and recycled by default.
You can change the number of cards created at the same time by setting [visible count](https://github.com/yuyakaido/CardStackView#visible-count).
