### ISSUE TITLE
how to get visible card by position

### ISSUE THREAD

**Issue by JenyaKirmizaTripTop** [yuyakaido/CardStackView#34]
hi, i'm using app:stackFrom="top"
and i need to get the root view of the card that is located under current card. how can i do it? 
I can get current card using getTopView

btw thanks for good library

**Comment by yuyakaido** [comment]
@JenyaKirmizaTripTop Currently, There is no way to get card by position. I try to develop this feature in my free time.

**Comment by JenyaKirmizaTripTop** [comment]
@yuyakaido  that's cool. I've managed to do it

**Comment by Jay268** [comment]
@JenyaKirmizaTripTop  How did you get it managed ? Could you explain bit more ? I wanted to show card for specific position like if i select 3rd item from recycle view and opens up detail screen so directly i wanted to show 3rd position data on card.

**Comment by yuyakaido** [comment]
Sorry, I have no plan to develop this feature.

**Comment by minageorge5080** [comment]
you can do this to get visible card position 

manger = new CardStackLayoutManager(this, new CardStackListener() {
           @Override
           public void onCardDragging(Direction direction, float ratio) {

           }

           @Override
           public void onCardSwiped(Direction direction) {

           }

           @Override
           public void onCardRewound() {

           }

           @Override
           public void onCardCanceled() {

           }

           @Override
           public void onCardAppeared(View view, int position) {
               Toasty.success(mContext,""+position,Toasty.LENGTH_SHORT).show();

           }

           @Override
           public void onCardDisappeared(View view, int position) {

           }
       });
