### ISSUE TITLE
How to remove the extra button area / bottom margin?

### ISSUE THREAD

**Issue by iWillBeUnderYourBed** [yuyakaido/CardStackView#345]
Under the Cards themselves, there is an area for the buttons, some kind of bottom margin. I don't now how to get rid of this space:

![Untitled](https://user-images.githubusercontent.com/49525679/121015140-f0932c00-c79a-11eb-9098-842d1137b81a.png)

When I have no buttons, this space is still being reserved, and just looks bad.

**Comment by yuyakaido** [comment]
@iWillBeUnderYourBed 
You need to remove or modify buttons container because it has fixed height.

```
            <RelativeLayout
                android:id="@+id/button_container"
                android:orientation="horizontal"
                android:layout_width="match_parent"
                android:layout_marginBottom="8dp"
                android:layout_height="80dp"
                android:layout_alignParentBottom="true"
                android:clipChildren="false">
```
