### ISSUE TITLE
Failed to resolve: com.yuyakaido.android:card-stack-view:2.3.4

### ISSUE THREAD

**Issue by xzyang123** [yuyakaido/CardStackView#358]
Dear Yuya Kaido,

Really appreciate your efforts in this amazing library. However, when I try to sync, this error message shows up.

Could you give me some suggestions?

<img width="768" alt="Screen Shot 2022-02-24 at 4 43 24 PM" src="https://user-images.githubusercontent.com/61488535/155631744-64ceded5-f4cc-4d81-995e-c79a3702e019.png">

Thank you so much.

Yang

**Comment by wasibhussain** [comment]
@xzyang123 where did you put the jcenter? as i was coming through the solutions, i found that removing jcenter and adding mavenCentral will resolve the error.. what about yours?

**Comment by aliraza96** [comment]
Instead of implementing it like this, do it like this, and the problem will get solved. Just did it myself

implementation("com.github.yuyakaido:cardstackview:2.3.4")
