### ISSUE TITLE
com.android.tools.build:gradle:3.0.0 Slow down the dragging

### ISSUE THREAD

**Issue by blackcolt** [yuyakaido/CardStackView#36]
When you upgrade your build:gradle to 3 the dragging processes of the card stack is slow down (dramatically). 

My File:

```
buildscript {
    repositories {
        jcenter()
        google()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.gms:google-services:3.0.0'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```
Workaround:
For now I just rollback to 2.3.3 And everything went to normal.

**Comment by yuyakaido** [comment]
@blackcolt I can't reproduce this performance issue...
I pushed test branch as https://github.com/yuyakaido/CardStackView/tree/issue/36.

Can you confirm whether or not to reproduce with this branch?

My environment is below.
- macOS Sierra 10.12.6
- Android Studio 3.0
- Nexus 5X (Android 8.0.0)
- Java Compiler 1.8.0_144

**Comment by blackcolt** [comment]
Found the problem:
in my manifest  android:hardwareAccelerated="false"
