### ISSUE TITLE
Dependency from README doesn't work.

### ISSUE THREAD

**Issue by Hiravi** [yuyakaido/CardStackView#371]
Dependency implementation "com.yuyakaido.android:card-stack-view:2.3.4" from README doesn't work. When I started using this  implementation 'com.github.yuyakaido:cardstackview:2.3.4' everything was fine

**Comment by bekmnsrw** [comment]
have you solved this problem?

**Comment by bekmnsrw** [comment]
> Dependency implementation "com.yuyakaido.android:card-stack-view:2.3.4" from README doesn't work. When I started using this implementation 'com.github.yuyakaido:cardstackview:2.3.4' everything was fine

have you solved this problem?

**Comment by Hiravi** [comment]
Like I said, when I use 'com.github.yuyakaido:cardstackview:2.3.4' instead of dependency from README, everything works
