### ISSUE TITLE
Swipe is buggy (Not smooth)

### ISSUE THREAD

**Issue by RichieGladwin** [yuyakaido/CardStackView#38]
Swipe is not smooth in some android devices like OPPO CPH1701. How to make the swipe smoother in all devices?

**Comment by yuyakaido** [comment]
@RichieGladwin Please add more information such as version of CardStackView, Android OS, etc.

----

When you use `com.android.tools.build:gradle:3.0.0`, the dragging is slow down (#36)
I have no solution for this issue...

**Comment by RichieGladwin** [comment]
![screenshot 2](https://user-images.githubusercontent.com/22541563/32429683-b8ec9496-c2f1-11e7-8bee-916e079a4968.png)
  publishVersion = '1.0.0-beta5'

**Comment by yuyakaido** [comment]
@RichieGladwin Can you reproduce this issue on `1.0.0-beta8`?

**Comment by blackcolt** [comment]
Check you manifest for  android:hardwareAccelerated="false"
If its there - delete it

**Comment by RichieGladwin** [comment]
No i have not added any type like that in manifest.

**Comment by shikha1992** [comment]
i have added android:hardwareAccelerated="true". Does it effects card movement?

**Comment by yuyakaido** [comment]
@RichieGladwin @blackcolt @shikha1992 
[Ver. 2.0.0](https://github.com/yuyakaido/CardStackView/pull/137) has been released today! Try it out!

**Comment by shmakova** [comment]
Still not smooth

**Comment by ekashkin** [comment]
Probably not the best solution but try to remove rotation:
        cardStackLayoutManager.setMaxDegree(0.0f);
