### ISSUE TITLE
App crashes using CoordinatorLayout

### ISSUE THREAD

**Issue by Alyon91** [yuyakaido/CardStackView#41]
Using the CoordinatorLayout in the card item xml makes the app to crash.
Just try to add a CoordinatorLayout in the item_tourist_spot_card.xml in the sample project, and see the issue.

**Comment by Alyon91** [comment]
ok i found what was causing the problem: when creating the Adapter, the line was:
`final TouristSpotCardAdapter adapter = new TouristSpotCardAdapter(getApplicationContext());`
but to work with an appcompat theme, `getApplicationContext()` should be changed with `this`.
I suggest to update the sample project like that, so it's more flexible.

**Comment by yuyakaido** [comment]
@Alyon91 
This issue has been fixed in ver. 2.1.1.
