### ISSUE TITLE
Disable left or right swipe?

### ISSUE THREAD

**Issue by Shrikant-B** [yuyakaido/CardStackView#44]
Hello again, 

I have a question regarding swipe direction. 
I know there is 
```
<com.yuyakaido.android.cardstackview.CardStackView
    app:swipeEnabled="true"
    or
    app:swipeEnabled="false"/>
```
OR

```
CardStackView#setSwipeEnabled(true);
or
CardStackView#setSwipeEnabled(false);
```
for enable or disable swipe.

But is there any way I can allow swiping only in one direction? 
i.e, if I can disable swipping to right and only allow to swipe left or viceversa.

Thanks.

**Comment by ShrikantBadwaik-007** [comment]
Never mind i manage to do it like this: 
```
List<SwipeDirection> swipeDirection = new ArrayList<>();
swipeDirection.add(SwipeDirection.Left);
cardStackView.setSwipeDirection(swipeDirection);
```

**Comment by Jeel-Shah** [comment]
You can change the swipe direction by going into `cardstackview/SwipeDirection.java` and replacing say `HORIZONTAL` with `Arrays.asList(SwipeDirection.Right);`. In other words, you can add/remove/replace directions in that file.

**Comment by ShrikantBadwaik-007** [comment]
```
List<SwipeDirection> swipeDirectionList = new ArrayList<>();
swipeDirectionList.add(SwipeDirection.Left);
cardStackView.setSwipeDirection(swipeDirectionList );
```
This is what I have tried and works fine but my card can still roam around top-bottom-right and comes back to its original position. 
What I need is to prevent card from roaming around in other directions except Left i.e, allow user to swipe Left only. If he tries to move card in other direction, card shouldn't move at all.

**Comment by yuyakaido** [comment]
@Shrikant-B 
Sorry, I can't understand your use case.
[Ver. 2.0.0](https://github.com/yuyakaido/CardStackView/pull/137) supports [swipe direction](https://github.com/yuyakaido/CardStackView#swipe-direction) and [swipe restriction](https://github.com/yuyakaido/CardStackView#swipe-restriction), maybe you can implement with them.
