### ISSUE TITLE
How can I get the coordinates of the user's click on a card?

### ISSUE THREAD

**Issue by Jeel-Shah** [yuyakaido/CardStackView#47]
Hello,

Is there a way for me to receive the point (x,y) where the user clicked on the card? My approach is to do the following:

1. Update `CardContainerView.java` to pass `motionOriginX` and `motionOriginY` to the `containerEventListener`
2. `containerEventListener` will then pass them to `cardEventListener` in `CardStackView.java` and from there I can use the point as I need them?

Thanks for your time

**Comment by Jake-hyuk** [comment]
@Jeel-Shah 
 Your class extends CardStackView
@Override
    public boolean onInterceptTouchEvent(MotionEvent ev)
    {  
         // ev.getX() <-- here
        return super.onInterceptTouchEvent(ev);
    }
