### ISSUE TITLE
Block movement on horizontal or vertical axis.

### ISSUE THREAD

**Issue by temadu** [yuyakaido/CardStackView#48]
Is there any easy way to stop the card from moving in a specific axis? Like in the following gif where the horizontal axis is blocked and it can only move in the vertical axis.

![Vertical Swiper](https://github.com/alexbrillant/react-native-deck-swiper/raw/master/animation2.gif)

Thanks!

**Comment by Lokeshroot** [comment]
I an facing same issue!

**Comment by af-dre** [comment]
In method updateTranslation(MotionEvent event) in CardContainerView.java you can comment out ViewCompat.setTranslationX for a vertical drag constraint or likewise for translationY for a horizontal constraint

**Comment by yuyakaido** [comment]
@temadu @Lokeshroot @af-dre 
[Ver. 2.0.0](https://github.com/yuyakaido/CardStackView/pull/137) supports this feature as [swipe restriction](https://github.com/yuyakaido/CardStackView#swipe-restriction).
