### ISSUE TITLE
cardswipe with viewpagerindicator

### ISSUE THREAD

**Issue by PrashantAryan** [yuyakaido/CardStackView#49]
Hey yuyakaido,
how to implement card swipe with image swipe like as badoo app in your CardStackView

**Comment by loctra** [comment]
Same my issue!

**Comment by Lokeshroot** [comment]
Same my issue!

**Comment by luongvo** [comment]
@PrashantAryan @loctra @Lokeshroot As my waiting PR #76, you could extend `CardStackView` and handle touch events for each cards. Fully example for this will be added when I have time 💃

**Comment by PrashantAryan** [comment]
Thanks.


*Thanks &Regards,*
*Ashutosh Srivastava*

*Android DeveloperRoot Info Solution Pvt Ltd.*

**Comment by luongvo** [comment]
@PrashantAryan please close #46

**Comment by luongvo** [comment]
@PrashantAryan No, I mean you should close #46 and leave this issue is opening for discussion

**Comment by ashkryab** [comment]
Same my issue!
