### ISSUE TITLE
Failed to resolve support-v4:25.0.4

### ISSUE THREAD

**Issue by h4ppysmile** [yuyakaido/CardStackView#52]
Hello!
I fail to get this support version.
I have also set my support lib to 25.+ version.

**Comment by gamma-co** [comment]
Hi ,
i have this problem too :(

**Comment by yuyakaido** [comment]
@h4ppysmile @gamma-co 
Sorry, I can't reproduce this problem.
[Ver. 2.0.0](https://github.com/yuyakaido/CardStackView/pull/137) has been released right now. Try it out.
