### ISSUE TITLE
Card ignores touch with overlay

### ISSUE THREAD

**Issue by D330** [yuyakaido/CardStackView#58]
Here is my overlay

```
<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:visibility="visible"
    app:cardBackgroundColor="#22000000"
    app:cardCornerRadius="6dp"
    app:cardElevation="0dp"
    app:cardUseCompatPadding="true">

    <com.beardedhen.androidbootstrap.AwesomeTextView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center"
        android:textSize="64sp"
        app:bootstrapBrand="danger"
        app:fontAwesomeIcon="fa_trash_o" />

</android.support.v7.widget.CardView>
```
My content card contains hard layout, but i think it not important. In my case, the card ignores touching anywhere, BUT on the edges of the card, the touch works! if I remove the `app:cardUseCompatPadding="true"` then the touches do not work anywhere, even at the edges. Library bug? I use beta-8

**Comment by D330** [comment]
I removed all the content from the card, but the touch is still ignored, why does it work in the application sample?

**Comment by yuyakaido** [comment]
@D330 
[Ver. 2.0.0](https://github.com/yuyakaido/CardStackView/pull/137) has been released today! Try it out!
