### ISSUE TITLE
Let parent handle rest of the touch events if swipe direction provided by user

### ISSUE THREAD

**Issue by santalu** [yuyakaido/CardStackView#63]
For example if user set swipe direction to horizontal cardStackView should let parent handle vertical touch events and vice versa. 
Otherwise it's really hard to use this library within scrollView or coordinatorLayout etc.

**Comment by yuyakaido** [comment]
@santalu 
This issue has been fixed in [ver. 2.0.0](https://github.com/yuyakaido/CardStackView/pull/137).
