### ISSUE TITLE
Drag is not working if item is clickable

### ISSUE THREAD

**Issue by rajatgupta0889** [yuyakaido/CardStackView#67]
Hi 
The drag event is not working on the card if we put a clickListener on the view inside

**Comment by luongvo** [comment]
@rajatgupta0889 I submit a PR to support this issue, it's waiting for merging. You could check and use our snapshot at https://jitpack.io/#Buddify/CardStackView/support_card_container_view_customizable-SNAPSHOT

**Comment by luongvo** [comment]
Check PR above for example

**Comment by shikha1992** [comment]
is there any solution to this issue so far?

**Comment by luongvo** [comment]
@shikha1992 https://github.com/yuyakaido/CardStackView/issues/67#issuecomment-368947458

**Comment by yuyakaido** [comment]
@rajatgupta0889 @luongvo @shikha1992 @monowar1993 
This issue has been fixed in ver. 2.1.1.
