### ISSUE TITLE
Perform reverse by draggin

### ISSUE THREAD

**Issue by mpierucci** [yuyakaido/CardStackView#72]
Is there a way to perform a reverse (bring previous card back) by dragging from the edge of the screen?

**Comment by sheetalsuryan** [comment]
Is there a way to perform a reverse (bring previous card back) by dragging from the edge of the screen? and disable right  dragging

**Comment by luongvo** [comment]
There is no way for now @mpierucci

**Comment by mpierucci** [comment]
I do have a PR ready for that action, let me know if would like to see it

**Comment by luongvo** [comment]
@mpierucci which one?

**Comment by ZaydelEduard** [comment]
@mpierucci Hey, can you share your code as pull request?

**Comment by enriquebautista** [comment]
@mpierucci Hi! can you share your code to perform reverse by draggin. Thanks

**Comment by yuyakaido** [comment]
Sorry, I have no plan to develop this feature.
