### ISSUE TITLE
onCardSwiped() is not called on time

### ISSUE THREAD

**Issue by barakhadar** [yuyakaido/CardStackView#74]
I'm trying to prevent users from swiping fast, as the onCardSwiped() is called with a delay on fast swiping. 

If a user swipes fast, by the time the user is on his 3rd swipe, the onCardSwiped() method get called on behalf of the 1st swipe.

I tried to disable swipes until the onCardSwiped() get called, like in the following code snippet, but it's not working as the current swipe get disabled too.

            `mCardsViewListener = new CardStackView.CardEventListener() {
                @Override
                public void onCardDragging( float percentX, float percentY ) {
                    if ( percentX >= 0.75 || percentX <= -0.75 ) {
                        mCardsView.setSwipeEnabled( false );
                    }
                }
        
                @Override
                public void onCardSwiped( SwipeDirection direction ) {
                    mCardsView.setSwipeEnabled( true );
                    // Some code to handle swiped card goes here...
                }
        
                @Override
                public void onCardReversed() {
                    Log.d( TAG, "onCardReversed" );
                }
        
                @Override
                public void onCardMovedToOrigin() {
                    Log.d( TAG, "onCardMovedToOrigin" );
                }
        
                @Override
                public void onCardClicked( int index ) {
                    Log.d( TAG, "onCardClicked: " + index );
                }
            };`

Is there a simple solution for this issue?
Thanks a lot

**Comment by yuyakaido** [comment]
@barakhadar 
Sorry for late reply.
This issue has been fixed in [ver. 2.0.0](https://github.com/yuyakaido/CardStackView/pull/137).
