### ISSUE TITLE
Second card is draggable after reversed the first ignored card

### ISSUE THREAD

**Issue by luongvo** [yuyakaido/CardStackView#79]
Steps to reproduce:
- Swipe any the first card (any direction)
- Reverse that card back
- While dragging that card to the left, we could drag the second too

![image](https://user-images.githubusercontent.com/16315358/37028866-191b53d2-2168-11e8-9ed2-ddb47669b000.png)

**Comment by yuyakaido** [comment]
@luongvo 
Sorry for late reply.
This issue has been fixed in [ver. 2.0.0](https://github.com/yuyakaido/CardStackView/pull/137).
