### ISSUE TITLE
Elevation cards

### ISSUE THREAD

**Issue by ivandiazmolina** [yuyakaido/CardStackView#8]
How can I remove the card's elevation to set cardview in fullscreen?

Thx

**Comment by yuyakaido** [comment]
@ivandiazmolina Do you want to remove this elevation?

<img width="360" alt="screen shot 2016-10-20 at 21 47 03" src="https://cloud.githubusercontent.com/assets/6598880/19560315/ee2fb076-970e-11e6-8a0d-b59bd516f762.png">

**Comment by ivandiazmolina** [comment]
@yuyakaido Yes

**Comment by yuyakaido** [comment]
@ivandiazmolina Okay. I implement this feature in weekend. Could you give me a few days?

**Comment by ivandiazmolina** [comment]
@yuyakaido Thx mate!

**Comment by yuyakaido** [comment]
@ivandiazmolina I will add setter method to set flag for elevation. How is this?

`CardStackView#setElevationEnabled(boolean enabled)`

In order to disable card elevation, just call `setElevatoinEnabled(false)` regardless of fullscreen

**Comment by yuyakaido** [comment]
@ivandiazmolina `0.7.6` is now available!
All you need is just call `CardStackView#setElevationEnabled(false)`

**Comment by yuyakaido** [comment]
@ivandiazmolina Ver `0.7.7` is also available with some improvements.
