### ISSUE TITLE
Blinking effects on touch event

### ISSUE THREAD

**Issue by syde0** [yuyakaido/CardStackView#82]
I want to start with thank you for making this library.

Now the issue, If i were to click or drag the card, a flickering/blinking effect will occur, I noticed that this only happened when my card is rich with layouts (layouts within layouts). 

No flickering happened if its just a simple tree layout though just like in the demo. I tried to make mine simple but some widget like Ratingbar is still flickering inside the card, any solutions?

**Comment by yuyakaido** [comment]
@syde0 
This problem has been fixed in [ver. 2.0.0](https://github.com/yuyakaido/CardStackView/pull/137).

**Comment by asifrpatel** [comment]
Still in 2.3.4 version

**Comment by Preetham288** [comment]
Still exits in 2.3.4 version

**Comment by ilaxopavan** [comment]
it works properly in 2.0.0 but not working in latest version strange behaviour
