### ISSUE TITLE
Calling secont

### ISSUE THREAD

**Issue by saikiran143** [yuyakaido/CardStackView#83]
Second time if i called adapter, it's not loading view. When we call adapter second time it's not showing any card.please fix ASAP.

**Comment by luongvo** [comment]
what do you mean `Second time if i called adapter`, show me your code

**Comment by PMARZV** [comment]
@luongvo I know this is 5 years later but its happening to me too
Code: `class DiscoverFragment : Fragment() , CardStackListener {

    private var _binding: FragmentDiscoverBinding? = null
    private val binding get() = _binding!!


    private val cardStackView by lazy { binding.cardStackView }
    private val manager by lazy { CardStackLayoutManager(requireContext(), this) }
    private lateinit var  adapter: SimpleGenericRecyclerAdapter<Spot>


    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
         _binding = FragmentDiscoverBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)


        binding.appbar.searchbarcard.apply{
            backgroundTintList = ColorStateList.valueOf(requireContext().AccentColorTransMain())
        }


        binding.appbar.toolbar.apply {
            setOnClickListener {
                val directions = TopTracksFragmentDirections.toSearchFragment()
                findNavController().navigateSafe(directions, null)
            }
            setNavigationOnClickListener {
                Toast.makeText(requireContext(), "toastText2" , Toast.LENGTH_SHORT).show()

            }
        }
        binding.appbar.appbarlayout.setLiftable(false)


        binding.likeButton.setOnClickListener{

            val setting = SwipeAnimationSetting.Builder()
                .setDirection(Direction.Right)
                .setDuration(Duration.Normal.duration)
                .setInterpolator(AccelerateInterpolator())
                .build()
            manager.setSwipeAnimationSetting(setting)
            cardStackView.swipe()
        }
        binding.skipButton.setOnClickListener{
            val setting = SwipeAnimationSetting.Builder()
                .setDirection(Direction.Left)
                .setDuration(Duration.Normal.duration)
                .setInterpolator(AccelerateInterpolator())
                .build()
            manager.setSwipeAnimationSetting(setting)
            cardStackView.swipe()
        }
        binding.rewindButton.setOnClickListener{
            val setting = RewindAnimationSetting.Builder()
                .setDirection(Direction.Bottom)
                .setDuration(Duration.Normal.duration)
                .setInterpolator(DecelerateInterpolator())
                .build()
            manager.setRewindAnimationSetting(setting)
            cardStackView.rewind()
        }

        val bindingInterface = object: GenericSimpleRecyclerBindingInterface<Spot> {
            override fun bindData(item:Spot, view:View){

                val textView: TextView = view.findViewById(R.id.item_city)
                val textView1: TextView = view.findViewById(R.id.item_name)
                val image: ImageView = view.findViewById(R.id.item_image)
                val card: CardView = view.findViewById(R.id.cardview)
                Glide.with(image)
                    .load(item.url)
                    .into(image)
                textView1.text = "${item.id}. ${item.name}"
                textView.text = item.city
                card.backgroundTintList = ColorStateList.valueOf(requireContext().AccentColorTransMain())


                view.setOnClickListener { v ->
                    Toast.makeText(v.context, item.name, Toast.LENGTH_SHORT).show()
                }
            }
        }
        adapter = SimpleGenericRecyclerAdapter(createSpots(), R.layout.item_spot, bindingInterface)

        setupCardStackView()







cardStackView.setHasFixedSize(true)










    }




    override fun onCardDragging(direction: Direction, ratio: Float) {
        Log.d("CardStackView", "onCardDragging: d = ${direction.name}, r = $ratio")
    }

    override fun onCardSwiped(direction: Direction) {
        Log.d("CardStackViewSWIPED", " ${manager.topPosition},$direction, ${adapter.itemCount}")

        if (manager.topPosition == adapter.itemCount) {
            paginate()
        }
    }

    override fun onCardRewound() {
        Log.d("CardStackView", "onCardRewound: ${manager.topPosition}")
    }

    override fun onCardCanceled() {
        Log.d("CardStackView", "onCardCanceled: ${manager.topPosition}")
    }

    override fun onCardAppeared(view: View, position: Int) {

    }

    override fun onCardDisappeared(view: View, position: Int) {

    }

    private fun setupNavigation() {
        // Toolbar

        // DrawerLayout


        // NavigationView

    }

    private fun setupCardStackView() {
        initialize()
    }





    private fun initialize() {
        manager.setStackFrom(StackFrom.Top)
        manager.setVisibleCount(3)
        manager.setTranslationInterval(8.0f)
        manager.setScaleInterval(0.90f)
        manager.setSwipeThreshold(0.3f)
        manager.setMaxDegree(-60.0f)
        manager.setDirections(Direction.FREEDOM)

        manager.setCanScrollHorizontal(true)
        manager.setCanScrollVertical(true)
        manager.setSwipeableMethod(SwipeableMethod.AutomaticAndManual)
        manager.setOverlayInterpolator(DecelerateInterpolator())
        cardStackView.layoutManager = manager
        cardStackView.adapter = adapter
        cardStackView.itemAnimator.apply {
            if (this is DefaultItemAnimator) {
                supportsChangeAnimations = false
            }
        }
    }

    private fun paginate() {
        val old = adapter.getData()

        val new = old.plus(createSpots())
        val callback = SpotDiffCallback(old, new)
        val result = DiffUtil.calculateDiff(callback)
        adapter.setData(new)
        result.dispatchUpdatesTo(adapter)
    }

    private fun reload() {
        val old = adapter.getData()
        val new = createSpots()
        val callback = SpotDiffCallback(old, new)
        val result = DiffUtil.calculateDiff(callback)
        adapter.setData(new)
        result.dispatchUpdatesTo(adapter)
    }




    private fun createSpots(): List<Spot> {
        val spots = ArrayList<Spot>()
        spots.add(Spot(name = "Yasaka Shrine", city = "Kyoto", url = "https://i.scdn.co/image/ab67616d0000b2731e212a6eff9f90acc8a2ff51"))
        spots.add(Spot(name = "Fushimi Inari Shrine", city = "Kyoto", url = "https://i.scdn.co/image/ab67616d0000b2731e212a6eff9f90acc8a2ff51"))
        spots.add(Spot(name = "Bamboo Forest", city = "Kyoto", url = "https://i.scdn.co/image/ab67616d0000b2731e212a6eff9f90acc8a2ff51"))
        spots.add(Spot(name = "Brooklyn Bridge", city = "New York", url = "https://i.scdn.co/image/ab67616d0000b2731e212a6eff9f90acc8a2ff51"))
        spots.add(Spot(name = "Empire State Building", city = "New York", url = "https://i.scdn.co/image/ab67616d0000b2731e212a6eff9f90acc8a2ff51"))
        spots.add(Spot(name = "The statue of Liberty", city = "New York", url = "https://i.scdn.co/image/ab67616d0000b2731e212a6eff9f90acc8a2ff51"))
        spots.add(Spot(name = "Louvre Museum", city = "Paris", url = "https://i.scdn.co/image/ab67616d0000b2731e212a6eff9f90acc8a2ff51"))
        spots.add(Spot(name = "Eiffel Tower", city = "Paris", url = "https://i.scdn.co/image/ab67616d0000b2731e212a6eff9f90acc8a2ff51"))
        spots.add(Spot(name = "Big Ben", city = "London", url = "https://i.scdn.co/image/ab67616d0000b2731e212a6eff9f90acc8a2ff51"))
        spots.add(Spot(name = "Great Wall of China", city = "China", url = "https://i.scdn.co/image/ab67616d0000b2731e212a6eff9f90acc8a2ff51"))
        return spots
    }

    override fun onResume() {
        super.onResume()
        cardStackView.layoutManager = manager
        cardStackView.adapter = adapter
    }
}`
When with navigate with Navigation component single top to another fragment when returning back there is no cards and the logcat says = No adapter attached; skipping layout. And when i try to add an adapter in on resumed it says that there already is an adapter.  I need urgent help!!
