### ISSUE TITLE
re-adding an item doesn't work

### ISSUE THREAD

**Issue by cesards** [yuyakaido/CardStackView#9]
Whenever I add an item, remove it, and adding another one, doesn't work.

After debugging for a bit, I've discovered it's related to `topIndex`, because once you remove an item from the adapter, this index is not updated. I'll try to fork the lib and dig into it, but if you could have a look would be amazing :-)

Thanks in advance.

**Comment by yuyakaido** [comment]
@cesards Sorry for late reply...
Thank you for your detail information!!
I investigate this issue, and fix it in a few days.

**Comment by yuyakaido** [comment]
@cesards Sorry for late reply...
Thank you for detail information!!
I investigate this issue, and fix it in a few days.

**Comment by NooruddinLakhani** [comment]
@yuyakaido have you fixed this issue ?

**Comment by yuyakaido** [comment]
@cesards @NooruddinLakhani Sorry for late reply. This issue is fixed in [ver. 1.0.0](https://github.com/yuyakaido/CardStackView/pull/14).
We should call notifyDataSetChanged() of adapter.

**Comment by yuyakaido** [comment]
@cesards @NooruddinLakhani Ver 1.0.0-beta1 has been released!
