### ISSUE TITLE
get last arraylist

### ISSUE THREAD

**Issue by Chingiz** [yuyakaido/CardStackView#96]
I want to get the latest arraylist. User swipes left or right and item removes from the screen, but I cannot get that arraylist. Even passing from adapter doesn't help.

**Comment by arwinf** [comment]
You do not swipe a full arraylist, but an single element of the adapter.. You like to get the last item you swiped?

**Comment by Chingiz** [comment]
When I am swiping items, items dismiss, but they are not removed from arraylist. How should I get latest array of elements in cardstackview?

**Comment by yuyakaido** [comment]
@Chingiz 
This library does not make any changes to its data source.
If you want to remove an item from data source, you should handle this operation in your code
