### ISSUE TITLE
Re-populating Adapter doesn't reset CardStackView

### ISSUE THREAD

**Issue by c-b-h** [yuyakaido/CardStackView#99]
private DataSetObserver dataSetObserver = new DataSetObserver() {
        @Override
        public void onChanged() {
            boolean shouldReset = false;
            if (state.isPaginationReserved) {
                state.isPaginationReserved = false;
            } else {
                boolean isSameCount = state.lastCount == adapter.getCount();
                shouldReset = !isSameCount;
            }
            initialize(shouldReset);
            state.lastCount = adapter.getCount();
        }
    };

Due to the line that says `boolean isSameCount = state.lastCount == adapter.getCount()`, when populating an existing adapter with new data (with matching count), `CardStackView` interprets this as not to reset its state.

**Comment by luongvo** [comment]
@c-b-h Don't know why the author uses that flow, but I had submitted a PR for that https://github.com/yuyakaido/CardStackView/pull/93

**Comment by c-b-h** [comment]
I make sure to try out your change to see make it work. Thanks!

**Comment by yuyakaido** [comment]
@c-b-h @luongvo 
This problem has been fixed in [ver. 2.0.0](https://github.com/yuyakaido/CardStackView/pull/137).
